const appointments = [
  {
    appointmentID: "A1001",
    patientID: "P1001",
    doctorID: "D101",
    appointmentDate: "2023-12-01",
    time: "10:00",
    purpose: "Routine Checkup",
    notes: "Annual physical examination.",
  },
  {
    appointmentID: "A1002",
    patientID: "P1002",
    doctorID: "D101",
    appointmentDate: "2023-12-01",
    time: "11:00",
    purpose: "Routine Checkup",
    notes: "Annual physical examination.",
  },
  {
    appointmentID: "A1003",
    patientID: "P1003",
    doctorID: "D101",
    appointmentDate: "2023-12-01",
    time: "12:00",
    purpose: "Routine Checkup",
    notes: "Annual physical examination.",
  },
  {
    appointmentID: "A1004",
    patientID: "P1004",
    doctorID: "D101",
    appointmentDate: "2023-12-01",
    time: "13:00",
    purpose: "Routine Checkup",
    notes: "Annual physical examination.",
  },
  {
    appointmentID: "A1005",
    patientID: "P1005",
    doctorID: "D101",
    appointmentDate: "2023-12-01",
    time: "14:00",
    purpose: "Routine Checkup",
    notes: "Annual physical examination.",
  },
];
const patients = [
  {
    patientID: "P1001",
    name: "John Doe",
    dateOfBirth: "1980-01-01",
    medicalHistory: ["diabetes"],
    currentMedications: ["Metformin"],
    emergencyContact: "Jane Doe",
  },
  {
    patientID: "P1002",
    name: "Jane Doe",
    dateOfBirth: "1980-01-01",
    medicalHistory: ["diabetes"],
    currentMedications: ["Metformin"],
    emergencyContact: "John Doe",
  },
  {
    patientID: "P1003",
    name: "James Hollis",
    dateOfBirth: "1980-01-01",
    medicalHistory: ["diabetes"],
    currentMedications: ["Metformin"],
    emergencyContact: "Rob Sims",
  },
  {
    patientID: "P1004",
    name: "Ashley Arnold",
    dateOfBirth: "1980-01-01",
    medicalHistory: ["diabetes"],
    currentMedications: ["Metformin"],
    emergencyContact: "James Hollis",
  },
  {
    patientID: "P1005",
    name: "Rob Sims",
    dateOfBirth: "1980-01-01",
    medicalHistory: ["diabetes"],
    currentMedications: ["Metformin"],
    emergencyContact: "Ashley Arnold",
  },
];
module.exports = { appointments, patients };
